# Colors (Dracula)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#FFCB6B'
blue    = '#82AAFF'
magenta = '#C792EA'
cyan    = '#8be9fd'
white   = '#f8f9f2'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#FF6E6E'
green   = '#69FF94'
yellow  = '#FFCB6B'
blue    = '#D6ACFF'
magenta = '#ff92df'
cyan    = '#a4ffff'
white   = '#f8f8f2'
