# NOTE:https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd github config url
# import
import = [
  "~/.config/alacritty/themes/themes/dracula.toml",
  "~/.config/alacritty/fonts.toml",
]

# Live config reload (changes require restart)
live_config_reload = true

# This section documents the [window] table of the configuration file.
[window]
# window dimensions (changes require restart)
dimensions = { columns = 130, lines = 40 }
# window startup position.
position = "None"
# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
padding = { x = 3, y = 3 }
# Spread additional padding evenly around the terminal content.
dynamic_padding = true
# window decorations
decorations = "Buttonless"
# Background opacity as a floating point number from 0.0 to 1.0. The 
# value 0.0 is completely transparent and 1.0 is opaque.
opacity = 0.9
# Window title.
title = "Alacritty"
# Allow terminal applications to change Alacritty's window title.
# Default: true
dynamic_title = true

# This section document the [cursor] table of the configuration file.
[cursor]
style = { shape = "Block", blinking = "Always" }
# If the vi mode cursor style is "None" or not specified, it will fall
# back of the active value of the normal cursor.
vi_mode_style = { shape = "Block", blinking = "Always" }
# When this is true, the cursor will be rendered as a hollow box when 
# the window is not focused
unfocused_hollow = true
# Cursor blinking interval in milliseconds.
blink_interval = 700
# Time after which cursor stops blinking, in seconds.
# Specifying 0 will disable timout for blinking.
blink_timeout = 3

# This section documents the [terminal] talbe of the configuration file.
[terminal]
# Control the ability to write to the system clipboard with the OSC 52
# escape sequence. While this escape sequence is useful to copy contents
# from the remote server, allowing any application to read from the
# clipboard can be easily abused while not providing significant
# benefits over explicitly pasting text.
osc52 = "CopyPaste"
